server:
  port: 8081

spring:
  datasource:
    dynamic:
      primary: master # 默认数据源
      strict: false   # 未匹配到指定数据源时是否报错，false 为使用默认
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/task_manager?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        log: # 示例：执行记录等日志类表，可以切到这个数据源（目前可与 master 共用同一库）
          url: jdbc:mysql://localhost:3306/task_manager?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.task.entity
  configuration:
    map-underscore-to-camel-case: true


